### ISSUE TITLE
NS_ERROR_SOCKET_ADDRESS_IN_USE

### ISSUE THREAD

**Issue by exfann** [redecheck/redecheck-tool#3]
Not sure if this is just an issue with one of the linux components that I had to install manually, but it keeps giving me a socket in use error.
Here's some of the terminal output. It outputs the first one every time it opens a new instance of firefox, and then eventually quits with the second.

`1506812158870    geckodriver    INFO    geckodriver 0.19.0`
`1506812158876    geckodriver    INFO    Listening on 127.0.0.1:19253`
`Sep 30, 2017 6:55:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession`
`INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end`
`1506812159437    mozrunner::runner    INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.YSPZaMZarPWp"`
`1506812160782    Marionette    INFO    Listening on port 2828`
`Sep 30, 2017 6:56:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession`
`INFO: Falling back to original OSS JSON Wire Protocol.`
`1506812219835    mozrunner::runner    INFO    Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.rpQMbB6feMVV"`
`1506812220730    Marionette    ERROR    Error on starting server: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 111"  data: no]`
`[Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://marionette/content/server.js :: MarionetteServer.prototype.start :: line 111"  data: no]`
`MarionetteServer.prototype.start@chrome://marionette/content/server.js:111:19`
`MarionetteComponent.prototype.init@resource://gre/components/marionettecomponent.js:185:5`
`MarionetteComponent.prototype.handle@resource://gre/components/marionettecomponent.js:100:5`

`org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@76a3e297, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@76a3e297, version=, platform=ANY}], required capabilities = Capabilities [{}]`
`Build info: version: 'unknown', revision: 'unknown', time: 'unknown'`
`System info: host: 'fanne-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-35-generic', java.version: '1.8.0_131'`
`Driver info: driver.version: FirefoxDriver`
    `at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)`
    `at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)`
    `at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)`
    `at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)`
    `at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)`
    `at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)`
    `at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)`
    `at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)`
    `at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)`
    `at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:238)`
    `at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)`
    `at shef.utils.BrowserFactory.getNewDriver(BrowserFactory.java:23)`
    `at shef.main.RLGExtractor.extract(RLGExtractor.java:100)`
    `at shef.main.Tool.runFaultDetector(Tool.java:185)`
    `at shef.main.Tool.<init>(Tool.java:136)`
    `at shef.main.Tool.main(Tool.java:417)`

**Comment by exfann** [comment]
Alright, so I figured out that the reason for this was because I was using a version of geckodriver that was too new. Once I started using older ones, it worked fine.

**Comment by exfann** [comment]
For clarification, the browser is firefox 46. So far, geckodriver 0.19.0 is the only one that's broken it.
Geckodrivers 0.11.0, 0.12.0, and 0.13.0 are okay so far. I'll test out the others later and update on where it starts breaking.
